
[project]
name = 'nltms'
description = 'nltms, for nuLiga Tennis Match Scraper, scrapes tennis matches from liga.nu and returns them as a list of match objects'
version = '0.0.0'

requires-python = '>=3.12'
dependencies = [
	'requests == 2.32.3',
	'beautifulsoup4 == 4.13.4',
]
